version: '3'
services:
  mysql_hobeez_container:
    container_name: mysql_hobeez_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'HobeezDataBase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'hobeezDbUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'hobeezPassword34'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - /home/sql/hobeez/sql_vol:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    networks:
      - backend

  app:
    build: ./
    ports:
      - "997:8080"
    depends_on:
      - mysql_hobeez_container
    networks:
      - backend
    restart: always


networks:
  backend:
    driver: bridge

